
NUM_LAYERS = 2
DROPOUT = 0.5
BIDIRECTIONAL = True
NUM_DIRS = 2 if BIDIRECTIONAL else 1
WEIGHT_DECAY = 1e-4
SAVE_EVERY = 5
SHOW_ACCURACY = 1 # Epochs
EPOCHS = 100
BATCH_SIZE = 64 
EMBEDDING_DIM = 100
HIDDEN_DIM = 100
OPTIMIZER = 'ADAM' #ADAM, SDG
LEARNING_RATE = 0.008 if OPTIMIZER == 'ADAM' else 0.02 #SDG 0.02 ADAM 0.0005
USE_CUDA = False
TRAIN_DATA = 'data/train.enes.txt'
DEV_DATA = 'data/test_enes.txt'
